import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ScriptEval",
  description: "Generated by Cipher Wizard",
};
import { Toaster } from 'react-hot-toast';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
