import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ScriptEval",
  description: "Generated by Cipher Wizard",
};
import { Toaster } from 'react-hot-toast';
import { auth } from "@/lib/auth";
import { headers } from "next/headers";

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth.api.getSession({
    headers: await headers()
  });
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster position="top-center" />
        {session?.user && (
        <div className="absolute top-6 right-6 bg-indigo-50 border border-indigo-100 text-indigo-700 px-4 py-2 rounded-full text-sm font-medium shadow-sm flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-green-500"></span>
          Logged in as <span className="font-bold">{session.user.name}</span> ({session.user.email})
        </div>
      )}
      </body>
    </html>
  );
}
